### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#25]
These warning happen whenever I try to activate the pipeline. The pipeline work later. Does it need any fix?
Warning in system(cmd, intern = TRUE) :
  running command 'schtasks /Create /TN "epitweetr_detect_loop" /TR "cmd /c C:/PROGRA~1/R/R-40~1.4/bin/Rscript.exe \"C:/Users/azaghlool/epitweetr/detect.R\" \"E:/Twitter\" >> \"C:/Users/azaghlool/epitweetr/detect.log\" 2>&1" /SC HOURLY /ST 10:47 /SD "mm-dd-yy" /F' had status 16389
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/04/18 09:33:40 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Warning in system(cmd, intern = TRUE) :
  running command 'schtasks /Create /TN "epitweetr_detect_loop" /TR "cmd /c C:/PROGRA~1/R/R-40~1.4/bin/Rscript.exe \"C:/Users/azaghlool/epitweetr/detect.R\" \"E:/Twitter\" >> \"C:/Users/azaghlool/epitweetr/detect.log\" 2>&1" /SC HOURLY /ST 09:34 /SD "mm-dd-yy" /F' had status 16389

**Comment by lauespinosa** [comment]
Dear Abdou,

Can you please clarify what do you mean by activating the pipeline?

If you mean clicking on **'activate'** in the configuration page, that's only needed the first time. This warning is telling you that the tasks already exist in the Task Scheduler.

In order to **'activate'** the tasks from the Task Scheduler:
   1. Right click on each task and **'enable'** them (if tasks are disabled; otherwise, go to next step)
   2. Right click on each task and click on **'run'**
