### ISSUE TITLE
Error on dependencies download

### ISSUE THREAD

**Issue by iancg1** [EU-ECDC/epitweetr#38]
Good day! I'm trying to run epitweetr for the first time, but I am getting the following message on the configuration page:
<img width="960" alt="Screenshot 2021-09-24 090701" src="https://user-images.githubusercontent.com/37170525/134603260-2fc4022d-b0d5-48fb-a526-ee95f772a23f.png">

With the following view on the troubleshoot page:
<img width="960" alt="Screenshot 2021-09-23 164055" src="https://user-images.githubusercontent.com/37170525/134603370-b58ac2ad-37f2-46dd-950c-002c9d379375.png">

It seems that epitweetr is unable to open the URL for downloading CRAN JARs and winutils? How do I remedy this?

Thank you.

**Comment by forchard** [comment]
Hi @iancg1 !
Can you copy the text of the URL failing on this issue?
Are you able to access the specified URL from your machine?
Do you use a proxy for internet access?
Best regards,
Francisco

**Comment by iancg1** [comment]
Hi Francisco!

I got it to work by deactivating my VPN. However, the process is now stuck at the aggregate stage:
<img width="960" alt="Screenshot 2021-09-25 173442" src="https://user-images.githubusercontent.com/37170525/134766810-c7395129-f0a3-4e4e-921f-8ebea13b47a6.png">

![image](https://user-images.githubusercontent.com/37170525/134766831-1c9c130d-bc76-4876-bdd3-c879fcf104b5.png)

I've tried closing and re-opening R, as well as restarting my computer a few times to no avail. Any thoughts?

Thank you for your support!

**Comment by lauespinosa** [comment]
Hi @iancg1,

It is normal to get the errors in the diagnostic until epitweetr finishes the first "round" of aggregation and alerts. In the screenshot you shared with the detection pipeline, you can see that aggregation task was running and it hadn't finished yet.

Please consider that the first time, the aggregation may take longer since it has to process data for the past seven days. This applies also if you run epitweetr only once a week.

Relaunch the Shiny app and check if the task 4 (aggregation) in the detection pipeline appears as running. If it does, ensure the computer is on until it finishes. If it doesn't (failed or aborted), please click on "Run aggregate". In all these cases, you should have the detection loop running (either in the task scheduler or in an RStudio window, depending on which option you are using).

**Comment by iancg1** [comment]
Hi @lauespinosa ! Thank you very much for your support.

I will follow your recommendations and keep my computer running overnight so it can finish working on the aggregation task. Just a follow-up question. When I run epitweetr, two Windows cmd.exe are running. I think they are triggered when I run tweet search and detection pipeline. Is it safe to close these or do I have to keep them open?

Sorry for the very basic questions, I am very new to this and I'm still learning.

Best,
Ian

**Comment by lauespinosa** [comment]
Hi @iancg1 ,

Those cmd windows are running the search and detection pipelines. You must keep those in order to have the pipelines and tasks running. 

If you close them, you will see that the status in the configuration page of the tweet search and detection pipeline will appear as stopped with the letters in red.

No need to be sorry 🙂 
Let us know if you have any further question.

Best,

Laura
