### ISSUE TITLE
Geonames aborted

### ISSUE THREAD

**Issue by y24yang** [EU-ECDC/epitweetr#47]
Dear Laura/Francisco, 

I'm a first-time user of epitweetr.  While configuring the application on a web browser, I encountered the following error message after running Geonames. 

Max number of retries reached failed while assembling geonames Error in spark_job(paste("updateGeonames", conf_geonames_as_arg(), "assemble", : Error encountered while exeuting: java -cp "C:/Users/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/Documents/jars/*" -Xmx4g org.ecdc.twitter.Tweets updateGeonames geonamesSource "C:/Users/Documents/geo/allCountries.txt" geonamesDestination "C:/Users/Documents/geo" geonamesSimplify "TRUE" assemble "TRUE" index "FALSE" parallelism 4

I did run diagnostics and noticed the java_version was false
**java_version**	false	Error in if (check()) "ok" else "ko": argument is of length zero

Also noticed the following warning message on the R console (but unsure if they're related to the aborted Geonames). 
Warning in shell(tcmd) :
  '
call java -cp "C:/Users/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/Documents/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getSampleTweets tweetPath "C:/Users/Documents/tweets/search" pathFilter ".*2022\.01\.03.*" langCodes "en,fr,es,pt" langNames "English,French,Spanish,Portuguese" langPaths "C:/Users/Documents/languages/en.txt.gz,C:/Users/Documents/languages/fr.txt.gz,C:/Users/Documents/languages/es.txt.gz,C:/Users/Documents/languages/pt.txt.gz"  geonamesSource "C:/Users/Documents/geo/allCountries.txt" geonamesDestination "C:/Users/Documents/geo" geonamesSimplify "TRUE" langIndexPath "C:/Users/Documents/geo/lang_vectors.index" limit 100 parallelism 4 textCol text langCol lang >"C:\Users\AppData\Local\Temp\RtmpukHaG0\file490429a56646"' execution failed with error code 1

Would appreciate it if you could please advise how to fix the errors. 

Thanks for your time.

**Comment by lauespinosa** [comment]
Dear @y24yang ,

Thank you for your interest in epitweetr.

I believe this error is happening because you may have deleted or added new languages to the languages by default (English, Spanish, Portuguese and French).
You should first download those default languages and after, delete or add as needed.

To solve it, please ensure you only have those four languages selected and run again GeoNames.

Today we have submitted a new version to CRAN so you can download this new version. I am mentioning this because, being a first time user, it may be easier to install this new version from scratch. The new version has a new data architecture and storage, among other things, and it requires a transfer of the old data stored by epitweetr.

**Comment by y24yang** [comment]
Dear Laura, 

Thanks for the advice.  I did use the default languages (English, Spanish, Portuguese and French) while running GeoNames.  The issue persists.  I'll try the new version and see if that helps. 

Will keep you posted.

**Comment by forchard** [comment]
Hi @y24yang 
Do you have java installed on your machine? (what is your OS by the way)
Could you please try the following command on a command prompt and share the resutls:
> java -version
Thanks in advance
Francisco

**Comment by lauespinosa** [comment]
Hi @y24yang ,

Please let us know if it has been solved to close the issue.

Thanks!

**Comment by y24yang** [comment]
Dear Laura and Francisco, 

Thank you so much for your advice. The issue has been solved. Please close it at your end. 

Cheers!

**Comment by forchard** [comment]
User reported the issue as fixed
