### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by y24yang** [EU-ECDC/epitweetr#62]
Hello, 

I found that all date fields are only available for the current date; all previous and future dates are greyed out in the calendar across epitweetr. Any idea how to make all dates available? 

Thanks,

**Comment by forchard** [comment]
Hi @y24yang, 
Are you still having this issue?
When you just start collecting tweets it can only see tweets from last week because of Twitter API limitations. And it takes a while before epitweetr can build a history of tweets. For very popular topics like covid19 you may need to wait a week before seeing meaning full data.

If you keep collecting data without important interruptions you will be able to see larger time series.

Best,
Francisco

**Comment by forchard** [comment]
Hi @y24yang 
Since no more input has been provided I will close this issue.
Please feel free to reopen it if you still have issues.
Best
Francisco
