### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by eunyhwang** [EU-ECDC/epitweetr#69]
Dear Epitweetr Team,

I'm using Epitweetr with a Twitter Developer account and I've got "true" in green at the "twitter_auth" in the troubeshoot tap. But, when I run the "search_loop", I've got an authorization error saying like this: "Unauthorized by twitter APIi 403 Error in twitter_get(urls, i = i + 1, retries = retries, tryed = tryed): Unauthorized by twitter APIi 403"

Any helps would be appreciated!

Best, 
Eunyoung

**Comment by lauespinosa** [comment]
Dear @eunyhwang,

There are two possible reasons that come to my mind:

**1. Issue with the Twitter API v2**

Have you activated the Twitter API v2 in your Twitter Developer account? It is free but it requires an activation from the user in the Twitter Developer Portal (under Products > Twitter API v2).

You can quickly check if the issue is related to the API v2 by unselecting that in the configuration page and saving settings.

You can find more information on the 403 error from Twitter API [here](https://developer.twitter.com/en/support/twitter-api/error-troubleshooting).

**2. Issue with the credentials**

It can also be a typo with the credentials, in case you haven't checked already, or that you haven't saved the credentials (click on "save settings" at the end of the left column in the configuration page of the epitweetr Shiny app).

Best,

Laura

**Comment by forchard** [comment]
Dear @eunyhwang 

You may need to request elevated access since twitter is not allowing v1.1 access anymore without this option.
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#Access

You can do this for free on the developer portal.
@lauespinosa maybe we can modify the validation on the trouble shoot page to reflect this change on twitter policy.
Best,
Francisco

**Comment by eunyhwang** [comment]
Dear @lauespinosa and @forchard, 

Thank you for the quick reply! It's really weird that it works when I unselect the API v2 in the configuration page (i.e., no Twitter API version specified). FYI, I have activated the Twitter API v2 in my account and have Elevated access. Let me share the screenshot of the portal. 

![grafik](https://user-images.githubusercontent.com/49271495/171363890-1065220e-9183-4a7c-b18e-d37958096fc8.png)

Best,
Eunyoung

**Comment by eunyhwang** [comment]
Dear Epitweetr Team, 

unfortunately, I still don't get what was the problem of the authentication.. 

Also, I have another question: how can I run aggregate if I don't see the Run Aggregate button on the webapp? I tried to run it manually with this code: "epitweetr::get_aggregates()", but I get an error like this "Error in if (conf$onthefly_api) jsonlite::stream_in(url(q_url), verbose = FALSE) else { : argument is of length zero".

Thank you for your support in advance!

Best, 
Eunyoung

**Comment by forchard** [comment]
Hi @eunyhwang 
If you do not mind, lets keep this issue for the original problem which is authentication.
If  you have problems with aggregation please open another issue.

Concerning your authentication issue please share the results of the following code:
> token <- rtweet::get_token()
rtweet::search_tweets(q="hello")

and 
> epitweetr::setup_config('your data folder here')
epitweetr:::conf$api_version

Thanks,
Francisco

**Comment by eunyhwang** [comment]
Dear Francisco, 

here is the result of the codes. 
![grafik](https://user-images.githubusercontent.com/49271495/172374808-e9351eba-9ffb-4ac9-867a-ad97aa4024a2.png)
I think the first line helps to solve the authentication issue. 

Best, 
Eunyoung

**Comment by eunyhwang** [comment]
Dear Francisco, 

here are the results.

![grafik](https://user-images.githubusercontent.com/49271495/172576968-88ff087d-b468-4598-b626-beaad87d81ab.png)
![grafik](https://user-images.githubusercontent.com/49271495/172577036-d519bb55-d007-496a-9f63-2f8e0548031f.png)

Somehow, the Dependecies and Geonames worked, but I got another error in the Laungages step: "Max number of retries reached failed while downloaded Spanish languages Error in curl::curl_fetch_memory(url, handle = handle): Recv failure: Connection was reset". I guess it's related to this authentication problem..

Best, 
Eunyoung

**Comment by forchard** [comment]
Hi @eunyhwang 
You should use your full path when running epitweetr.
You should replace
> epitweetr_setup_config("epi_trial_final")

by

> epitweetr_setup_config("E:/your home hee/some path/epti_trial_final")


of course youhave to change E:/your home hee/some path/epti_trial_final by the real path

Best,
Francisco

**Comment by eunyhwang** [comment]
Hi @forchard

sorry for the late reply!
Yes, you're right, I replace the path as you suggested and received this result.
![grafik](https://user-images.githubusercontent.com/49271495/176173368-398aed57-01ff-4a67-91e3-aaa0828daa00.png)

I still suffer Authentication problem. I assume it also raises this error on Configuration tab when I update Geonames:
failed while downloaded Spanish languages simpleWarning in open.connection(con, "rb"): InternetOpenUrl failed: 'A connection with the server could not be established' 

Best, 
Eunyoung

**Comment by eunyhwang** [comment]
Dear Epitweetr Team, 

this issue has been solved by renewing the app information and associating with the project again. You can close this issue. 
Thank you for your support!

Best, 
Eunyoung
