### ISSUE TITLE
Path of Aggregated Rds Files

### ISSUE THREAD

**Issue by eunyhwang** [EU-ECDC/epitweetr#74]
Dear Epitweetr Team, 

I don't know if this question is fitting to ask here, but I'm wondering where the aggregated file is saved on my device. Referring to the document, it is supposed to be saved under "series" folder containing Rds files, but I don't see the folder even after running Epitweetr perfectly. Maybe the document could be outdated or I did something wrong..

Here is the list of folders that I have got. 
![grafik](https://user-images.githubusercontent.com/49271495/183915517-6593ee66-cadb-4c94-8d54-8dac8d3666a5.png)

**Comment by eunyhwang** [comment]
Dear @forchard,

I'm still curios if the aggregated files have been saved well and if so where they are. I'm re-running epitweetr and getting this error which seems to be related to that issue. 
![grafik](https://user-images.githubusercontent.com/49271495/187429957-4b4678c5-1c34-429c-9b1c-7a7fc0ed449d.png)

Best, 
Eunyoung

**Comment by lauespinosa** [comment]
Dear @eunyhwang,

RDS are no longer produced by epitweetr since the latest release in January 2022.
Now, data is stored as Lucene indexes under `data_dir > fs` folder.

You can find this information in the [user documentation](https://cran.r-project.org/web/packages/epitweetr/vignettes/epitweetr-vignette.html) under **"Migrating to epitweetr v2"**.

The first time you run epitweetr, you may need to wait some minutes to rerun alerts tasks when there are at least some tweets collected and aggregated.
